version: "3"
services:
    django:
        restart: always 
        build: 
            context: . #build from this dir
            dockerfile: Dockerfile 
        volumes:
          - .:/app
          - static-volume:/app/static
          - media-volume:/app/media 
        command: sh -c "python manage.py makemigrations posts && python manage.py migrate && python manage.py makemigrations && python manage.py migrate && python manage.py collectstatic && gunicorn DjangoPostingSite.wsgi:application --bind 0.0.0.0:8000"
        networks:
          - web_network
    nginx: 
        restart: always 
        image: nginx:latest 
        ports: 
            - "80:80" 
        volumes:
            - static-volume:/app/static
            - media-volume:/app/media 
            - ./nginx/nginx.conf:/etc/nginx/nginx.conf
        depends_on:
            - django 
        networks:
            - web_network
volumes:
    static-volume:
    media-volume: 
networks:
    web_network:
        driver: bridge